config/routes.rb
Rails.application.routes.draw do
  root            'static_pages#home'
  devise_for      :users
  resources       :relationships,   only: [:create, :destroy]
  resources       :likes,           only: [:create, :destroy]
  resources       :users,           only: [:index, :show] do
    member do
      get         :following, :followers
    end
    resources     :posts,           only: [:show, :new, :create, :destroy] do
      resources   :comments,        only: [:new, :create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true,
            length: { minimum: 2, maximum: 360 }
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :image, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true,
            length: { minimum: 3 }, uniqueness: true

  def like(post)
    Like.create(post_id: post.id,
                user_id: self.id)
  end

  def likes?(post)
    likes.where(post_id: post.id).any?
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end

  private

    def logged_in?
      unless user_signed_in?
        flash[:alert] = "Please log in."
        redirect_to new_user_session_path
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "Comment successfully added"
      redirect_to [@comment.post.user, @comment.post]
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.user == current_user || @post.user
      @comment.destroy
      flash[:alert] = "Comment successfully deleted"
      redirect_to [@comment.post.user, @comment.post]
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in?
  before_action :set_post

  def create
    current_user.like(@post)
    respond_to do |format|
      format.html { redirect_to [@post.user, @post] }
      format.js
    end
  end

  def destroy
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
    respond_to do |format|
      format.html { redirect_to [@post.user, @post] }
      format.js
    end
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]
  before_action :correct_user?, only: :destroy

  def show
    @user = User.find(@post.user_id)
    @comments = @post.comments
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to [current_user, @post]
      flash[:notice] = "Post was successfully created."
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post was successfully destroyed."
    redirect_to current_user
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def correct_user?
    @user = User.find(@post.user_id)
    unless @user == current_user
      flash[:alert] = "You're not allowed to do that"
      redirect_to @user
    end

  end

  def post_params
    params.require(:post).permit(:content, :image)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in?

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in?

  def home
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "OOTD"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Add Comment</h1>

<%= form_for([@post.user, @post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', [@post.user, @post] %>

app/views/layouts/_header.html.erb
<ul>
  <% if user_signed_in? %>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Users", users_path %></li>
    <li><%= link_to "Settings", user_path(current_user) %></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Log in", new_user_session_path %></li>
  <% end %>
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/likes/create.js.erb
$("#like_form").html("<%= escape_javascript(render('posts/unlike')) %>");
$("#likes").html('<%= @post.likes.count %>');

app/views/likes/destroy.js.erb
$("#like_form").html("<%= escape_javascript(render('posts/like')) %>");
$("#likes").html('<%= @post.likes.count %>');

app/views/posts/_form.html.erb
<%= form_with(model: [current_user, post], local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_like.html.erb
<%= form_for(current_user.likes.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :post_id, @post.id %></div>
  <%= f.submit "Like" %>
<% end %>

app/views/posts/_like_form.html.erb
<div id="like_form">
  <% if current_user.likes?(@post) %>
    <%= render 'unlike' %>
  <% else %>
    <%= render 'like' %>
  <% end %>
</div>

app/views/posts/_unlike.html.erb
<%= form_for(current_user.likes.find_by(post_id: @post.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <div><%= hidden_field_tag :post_id, @post.id %></div>
  <%= f.submit "Unlike" %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', current_user %>

app/views/posts/show.html.erb
<%= image_tag @post.image.url if @post.image? %>
<p><%= @post.content %></p>

<p id="likes"><%= @post.likes.count %></p>

<%= render 'like_form' %>

<% @comments.each do |c| %>
  <p><%= c.content %> - <b><%= c.user.username %></b></p>
  <% if current_user == c.user || current_user == @post.user %>
    <%= link_to 'Delete Post', [current_user, @post, c], method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
<% end %>

<%= link_to "Comment", new_user_post_comment_path(post_id: @post.id) %>

<% if current_user?(@user) %>
  <%= link_to 'Back', @user %>
  <%= link_to 'Destroy', [current_user, @post], method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
<a href="<%= followers_user_path(@user) %>">
  <strong id="followers" class="stat">
    <%= @user.followers.count %>
  </strong>
  followers
</a>

app/views/static_pages/home.html.erb
<h2>Welcome <%= @user.username %></h2>
<%= render 'shared/stats' %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow" %>
<% end %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |u| %>
    <li><%= link_to u.username, u %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<%= render 'shared/stats' %>
<%= render 'follow_form' if user_signed_in? %>

<% @posts.each do |p| %>
  <%= link_to "Show", user_post_path(@user, p) %>
  <%= p.content %>
<% end %>

<% if current_user?(@user) %>
  <%= link_to "New Post", new_user_post_path(current_user) %>
<% end %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<h1><%= @user.username %></h1>
<%= link_to "view my profile", @user %>
<%= render 'shared/stats' %>


<h3><%= @title %></h3>
<% if @users.any? %>
  <% @users.each do |user| %>
    <%= link_to user.username, user %>
  <% end %>
<% end %>